---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: unifi-web-ingress-route
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`temp.unifi.leapshock.com`)
      kind: Rule
      services:
      - name: unifi-controller
        port: 8443
        scheme: https
        serversTransport: unifi-ingress-transport
---
apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: unifi-ingress-transport
spec:
  insecureSkipVerify: true
