---
apiVersion: v1
kind: Service
metadata:
  name: unifi-controller
spec:
  ports:
    - name: device-comm
      port: 8080
      protocol: TCP
    - name: stun
      port: 3478
      protocol: UDP
    - name: default-console
      port: 8443
      protocol: TCP
